### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by sadiqkhoja** [ot4i/DFDL-JSON-GDM-tutorial#6] opened 2016-07-19 06:22 UTC
I am using IIB v10 in Windows 10. I am not getting any output file in Cards folder. However same infput files are created in mqsibackout folder

**Comment by sadiqkhoja** [comment] 2016-07-19 08:10
User Trace Log have following info:

`<UserTrace timestamp="2016-07-19 06:42:12.133455" thread="11344" function="writeActivityLogEntry" text="&apos;Activity Log&apos;" catalog="BIPmsgs" number="13006" file="F:\build\S1000_slot1\S1000_P\src\DataFlowEngine\MessageServices\ImbActivityLogManager.cpp" line="502">
        <Insert type="string">&apos;3afd504c-1fef-43b4-8cba-1ed0b08bf1a8-vcard sample accept.txt&apos;</Insert>
        <Insert type="string">&apos;File Input&apos;</Insert>
    </UserTrace>
    <UserTrace timestamp="2016-07-19 06:42:12.133485" thread="11344" function="writeActivityLogEntry" text="&apos;Activity Log&apos;" catalog="BIPmsgs" number="11501" file="F:\build\S1000_slot1\S1000_P\src\DataFlowEngine\MessageServices\ImbActivityLogManager.cpp" line="502">
        <Insert type="string">&apos;File Input&apos;</Insert>
        <Insert type="string">&apos;Transform_vCards_into_JSON&apos;</Insert>
    </UserTrace>
    <UserTrace timestamp="2016-07-19 06:42:12.133527" thread="11344" function="ImbRootParser::parseNextItem" type="ComIbmFileInputNode" name="Transform_vCards_into_JSON#FCMComposite_1_1" label="Transform_vCards_into_JSON.File Input" text="&apos;Created parser&apos;" catalog="BIPmsgs" number="6063" file="F:\build\S1000_slot1\S1000_P\src\DataFlowEngine\MessageServices\ImbRootParser.cpp" line="670">
        <Insert type="string">&apos;Properties&apos;</Insert>
        <Insert type="integer">0</Insert>
        <Insert type="string">Transform_vCards_into_JSON.File Input</Insert>
    </UserTrace>
    <UserTrace timestamp="2016-07-19 06:42:12.133728" thread="11344" function="ImbDFDLUserTraceHandler::extractStatement" text="&apos;DFDL Info&apos;" catalog="BIPmsgs" number="5841" file="F:\build\S1000_slot1\S1000_P\src\MTI\MTIforBroker\DfdlParser\ImbDFDLUserTraceHandler.cpp" line="167">
        <Insert type="string">&apos;Offset: 0. Parsing will start from root element &apos;vCard&apos;.&apos;</Insert>
    </UserTrace>
    <UserTrace timestamp="2016-07-19 06:42:12.133822" thread="11344" function="ImbDFDLUserTraceHandler::extractStatement" text="&apos;DFDL Info&apos;" catalog="BIPmsgs" number="5841" file="F:\build\S1000_slot1\S1000_P\src\MTI\MTIforBroker\DfdlParser\ImbDFDLUserTraceHandler.cpp" line="167">
        <Insert type="string">&apos;Offset: 0. Starting to process element &apos;vCard&apos;.&apos;</Insert>
    </UserTrace>
    <UserTrace timestamp="2016-07-19 06:42:12.133862" thread="11344" function="ImbDFDLUserTraceHandler::extractStatement" text="&apos;DFDL Info&apos;" catalog="BIPmsgs" number="5841" file="F:\build\S1000_slot1\S1000_P\src\MTI\MTIforBroker\DfdlParser\ImbDFDLUserTraceHandler.cpp" line="167">
        <Insert type="string">&apos;Offset: 0. Did not find initiator for &apos;vCard&apos;&apos;</Insert>
    </UserTrace>
    <UserTrace timestamp="2016-07-19 06:42:12.133889" thread="11344" function="ImbDFDLUserTraceHandler::extractStatement" text="&apos;DFDL Info&apos;" catalog="BIPmsgs" number="5841" file="F:\build\S1000_slot1\S1000_P\src\MTI\MTIforBroker\DfdlParser\ImbDFDLUserTraceHandler.cpp" line="167">
        <Insert type="string">&apos;Offset: 0. Element &apos;vCard&apos; is empty because the initiator was not found in the data stream.&apos;</Insert>
    </UserTrace>
    <UserTrace timestamp="2016-07-19 06:42:12.133927" thread="11344" function="ImbDFDLUserTraceHandler::extractStatement" text="&apos;DFDL Fatal Error&apos;" catalog="BIPmsgs" number="5843" file="F:\build\S1000_slot1\S1000_P\src\MTI\MTIforBroker\DfdlParser\ImbDFDLUserTraceHandler.cpp" line="167">
        <Insert type="string">&apos;Initiator &apos;%WSP*;BEGIN%WSP*;:%WSP*;VCARD%CR;%LF;%WSP*;&apos; not found at offset &apos;0&apos;  for element &apos;/vCard[1]&apos;.&apos;</Insert>
    </UserTrace>
    <UserTrace timestamp="2016-07-19 06:42:12.133977" thread="11344" function="ImbDFDLErrorHandler::handleParserErrors" type="ComIbmFileInputNode" name="Transform_vCards_into_JSON#FCMComposite_1_1" label="Transform_vCards_into_JSON.File Input" text="&apos;An error occurred whilst parsing with DFDL&apos;" catalog="BIPmsgs" number="5807" file="F:\build\S1000_slot1\S1000_P\src\MTI\MTIforBroker\DfdlParser\ImbDFDLErrorHandler.cpp" line="143">
        <Insert type="string">&apos;CTDP3041E: Initiator &apos;%WSP*;BEGIN%WSP*;:%WSP*;VCARD%CR;%LF;%WSP*;&apos; not found at offset &apos;0&apos;  for element &apos;/vCard[1]&apos;.&apos;</Insert>
        <Insert type="string">Transform_vCards_into_JSON.File Input</Insert>
    </UserTrace>`

**Comment by LoveraSantiago** [comment] 2017-11-27 18:36
Hi to all.

Same problem here. No output in the expected address C:\IIB\Cards. When I did the project following this url tutorial:  http://ot4i.github.io/DFDL-JSON-GDM-tutorial/

I did a connection beetwen the failure port of the File Input node to MapNode and I got the follow error:

ParserException
	File:CHARACTER:F:\build\S1000_slot1\S1000_P\src\DataFlowEngine\MessageServices\ImbRootParser.cpp
	Line:INTEGER:879
	Function:CHARACTER:ImbRootParser::parseNextItem
	Type:CHARACTER:ComIbmFileInputNode
	Name:CHARACTER:Transform_vCards_into_JSON#FCMComposite_1_4
	Label:CHARACTER:Transform_vCards_into_JSON.File Input1
	Catalog:CHARACTER:BIPmsgs
	Severity:INTEGER:2
	Number:INTEGER:5902
	Text:CHARACTER:Exception whilst parsing
	Insert
			Type:INTEGER:5
			Text:CHARACTER:Root
	Insert
			Type:INTEGER:5
			Text:CHARACTER:DFDL
	Insert
			Type:INTEGER:5
			Text:CHARACTER:Stream Based Page Buffer [0,859] 424547494e3a56434152440a56455253494f4e3a322e310a4e3a4a6f686e3b446f776e0a464e3a4a6f686e20446f776e0a4f52473a536872696d7020436f2e0a5449544c453a4d722e0a50484f544f3b4749463a687474703a2f2f7777772e6578616d706c652e636f6d2f6469725f70686f746f732f6d795f70686f746f2e6769660a54454c3b574f524b3b564f4943453a2831313129203535352d313231320a54454c3b484f4d453b564f4943453a2834303429203535352d313231320a4144523b574f524b3a3b3b3130302057617465727320456467653b426179746f776e3b4c413b33303331343b556e6974656420537461746573206f6620416d65726963610a4c4142454c3b574f524b3b454e434f44494e473d51554f5445442d5052494e5441424c453a3130302057617465727320456467653d30443d3041426179746f776e2c204c412033303331343d30443d3041556e6974656420537461746573206f6620416d65726963610a4144523b484f4d453a3b3b343220506c616e746174696f6e2053742e3b426179746f776e3b4c413b33303331343b556e6974656420537461746573206f6620416d65726963610a4c4142454c3b484f4d453b454e434f44494e473d51554f5445442d5052494e5441424c453a343220506c616e746174696f6e2053742e3d30443d3041426179746f776e2c204c412033303331343d30443d3041556e6974656420537461746573206f6620416d65726963610a454d41494c3b505245463b494e5445524e45543a6a64406578616d706c652e636f6d0a534f554e443b56414c55453d55524c3a66696c652f2f2f6d756c74696d65642f617564696f2f6a717075626c69632e7761760a5549443a31393935303430312d3038303034352d3430303030463139323731332d303035320a5245563a3230303830343234543139353234335a0a4e4f54453b454e434f44494e473d51554f5445442d5052494e5441424c453a54657374696e67206573636170696e672d203a2073686f756c64206170706561722026202f3b20636f6d6d612073686f756c64206170706561722026202f0a202843524c46292073686f756c64206170706561722026202f2f2073686f756c64206170706561722c20616c6c20696e207468652073616d65206669656c64200a454e443a56434152440a
	Insert
			Type:INTEGER:14
			Text:CHARACTER:Transform_vCards_into_JSON.File Input1
	ParserException
			File:CHARACTER:F:\build\S1000_slot1\S1000_P\src\MTI\MTIforBroker\DfdlParser\ImbDFDLParser.cpp
			Line:INTEGER:506
			Function:CHARACTER:ImbDFDLParser::parseLastChild
			Type:CHARACTER:
			Name:CHARACTER:
			Label:CHARACTER:
			Catalog:CHARACTER:BIPmsgs
			Severity:INTEGER:3
			Number:INTEGER:5803
			Text:CHARACTER:DFDL parsing errors have occurred
			ParserException
					File:CHARACTER:F:\build\S1000_slot1\S1000_P\src\MTI\MTIforBroker\DfdlParser\ImbDFDLErrorHandler.cpp
					Line:INTEGER:166
					Function:CHARACTER:ImbDFDLErrorHandler::handleParserErrors
					Type:CHARACTER:ComIbmFileInputNode
					Name:CHARACTER:Transform_vCards_into_JSON#FCMComposite_1_4
					Label:CHARACTER:Transform_vCards_into_JSON.File Input1
					Catalog:CHARACTER:BIPmsgs
					Severity:INTEGER:3
					Number:INTEGER:5807
					Text:CHARACTER:An error occurred whilst parsing with DFDL
					Insert
							Type:INTEGER:5
							Text:CHARACTER:CTDP3041E: Initiator '%WSP*;BEGIN%WSP*;:%WSP*;VCARD%CR;%LF;%WSP*;' not found at offset '0'  for element '/vCard[1]'.

**Comment by LoveraSantiago** [comment] 2017-11-27 18:36
Next. I try to download the official zip here and I got this other error.

RecoverableException
	File:CHARACTER:F:\build\S1000_slot1\S1000_P\src\DataFlowEngine\MessageServices\ImbDataFlowNode.cpp
	Line:INTEGER:1251
	Function:CHARACTER:ImbDataFlowNode::createExceptionList
	Type:CHARACTER:ComIbmFileInputNode
	Name:CHARACTER:Transform_vCards_into_JSON#FCMComposite_1_1
	Label:CHARACTER:Transform_vCards_into_JSON.File Input
	Catalog:CHARACTER:BIPmsgs
	Severity:INTEGER:3
	Number:INTEGER:2230
	Text:CHARACTER:Node throwing exception
	Insert
			Type:INTEGER:14
			Text:CHARACTER:Transform_vCards_into_JSON.File Input
	ParserException
			File:CHARACTER:F:\build\S1000_slot1\S1000_P\src\DataFlowEngine\MessageServices\ImbRootParser.cpp
			Line:INTEGER:879
			Function:CHARACTER:ImbRootParser::parseNextItem
			Type:CHARACTER:ComIbmFileInputNode
			Name:CHARACTER:Transform_vCards_into_JSON#FCMComposite_1_1
			Label:CHARACTER:Transform_vCards_into_JSON.File Input
			Catalog:CHARACTER:BIPmsgs
			Severity:INTEGER:2
			Number:INTEGER:5902
			Text:CHARACTER:Exception whilst parsing
			Insert
					Type:INTEGER:5
					Text:CHARACTER:Root
			Insert
					Type:INTEGER:5
					Text:CHARACTER:DFDL
			Insert
					Type:INTEGER:5
					Text:CHARACTER:Stream Based Page Buffer [0,859] 424547494e3a56434152440a56455253494f4e3a322e310a4e3a4a6f686e3b446f776e0a464e3a4a6f686e20446f776e0a4f52473a536872696d7020436f2e0a5449544c453a4d722e0a50484f544f3b4749463a687474703a2f2f7777772e6578616d706c652e636f6d2f6469725f70686f746f732f6d795f70686f746f2e6769660a54454c3b574f524b3b564f4943453a2831313129203535352d313231320a54454c3b484f4d453b564f4943453a2834303429203535352d313231320a4144523b574f524b3a3b3b3130302057617465727320456467653b426179746f776e3b4c413b33303331343b556e6974656420537461746573206f6620416d65726963610a4c4142454c3b574f524b3b454e434f44494e473d51554f5445442d5052494e5441424c453a3130302057617465727320456467653d30443d3041426179746f776e2c204c412033303331343d30443d3041556e6974656420537461746573206f6620416d65726963610a4144523b484f4d453a3b3b343220506c616e746174696f6e2053742e3b426179746f776e3b4c413b33303331343b556e6974656420537461746573206f6620416d65726963610a4c4142454c3b484f4d453b454e434f44494e473d51554f5445442d5052494e5441424c453a343220506c616e746174696f6e2053742e3d30443d3041426179746f776e2c204c412033303331343d30443d3041556e6974656420537461746573206f6620416d65726963610a454d41494c3b505245463b494e5445524e45543a6a64406578616d706c652e636f6d0a534f554e443b56414c55453d55524c3a66696c652f2f2f6d756c74696d65642f617564696f2f6a717075626c69632e7761760a5549443a31393935303430312d3038303034352d3430303030463139323731332d303035320a5245563a3230303830343234543139353234335a0a4e4f54453b454e434f44494e473d51554f5445442d5052494e5441424c453a54657374696e67206573636170696e672d203a2073686f756c64206170706561722026202f3b20636f6d6d612073686f756c64206170706561722026202f0a202843524c46292073686f756c64206170706561722026202f2f2073686f756c64206170706561722c20616c6c20696e207468652073616d65206669656c64200a454e443a56434152440a
			Insert
					Type:INTEGER:14
					Text:CHARACTER:Transform_vCards_into_JSON.File Input
			ParserException
					File:CHARACTER:F:\build\S1000_slot1\S1000_P\src\MTI\MTIforBroker\DfdlParser\ImbDFDLParser.cpp
					Line:INTEGER:506
					Function:CHARACTER:ImbDFDLParser::parseLastChild
					Type:CHARACTER:
					Name:CHARACTER:
					Label:CHARACTER:
					Catalog:CHARACTER:BIPmsgs
					Severity:INTEGER:3
					Number:INTEGER:5803
					Text:CHARACTER:DFDL parsing errors have occurred
					ParserException
							File:CHARACTER:F:\build\S1000_slot1\S1000_P\src\MTI\MTIforBroker\DfdlParser\ImbDFDLErrorHandler.cpp
							Line:INTEGER:166
							Function:CHARACTER:ImbDFDLErrorHandler::handleParserErrors
							Type:CHARACTER:ComIbmFileInputNode
							Name:CHARACTER:Transform_vCards_into_JSON#FCMComposite_1_1
							Label:CHARACTER:Transform_vCards_into_JSON.File Input
							Catalog:CHARACTER:BIPmsgs
							Severity:INTEGER:3
							Number:INTEGER:5807
							Text:CHARACTER:An error occurred whilst parsing with DFDL
							Insert
									Type:INTEGER:5
									Text:CHARACTER:CTDP3041E: Initiator '%WSP*;BEGIN%WSP*;:%WSP*;VCARD%CR;%LF;%WSP*;' not found at offset '0'  for element '/vCard[1]'.

But It seens that we wont have any answer...

**Comment by Charlu90** [comment] 2018-01-10 15:20
Hi everyone,

FYI, I solved the problem will doing the tutorial.
The issue is that the given example files (vcard_XXX.txt) all have UNIX EOL characters.

To solve it, you just have to convert the EOL characters to Windows format 
With Notepad++, you just have to do this : 
Edit > EOL Conversion > Windows (CR LF)

**Comment by smhdfdl** [comment] 2019-11-12 10:27
The correct solution is to change the DFDL schemas to use `%NL;` instead of `%CR;%LF;`.  Fixed by #7.

**Closed as completed by smhdfdl** 2019-11-12 10:27 UTC
